import { icons } from './icons'


export const integrations = [
  {
    name: 'Insperity',
    icon: icons.insperityIcon,
    url: 'https://www.insperity.com/',
    description: 'Insperity is a professional employer organization (PEO) that provides human resources and administrative services to small and medium-sized businesses.',
    shortDescription: 'Insperity is a HRIS system',
    category: 'HRIS & Ben Admin',
    isActive: false,
  },
  {
    name: 'Paylocity',
    icon: icons.paylocityIcon,
    url: 'https://www.paylocity.com/',
    description: 'Paylocity is a cloud-based payroll and human capital management (HCM) platform that provides human resources and payroll management tools to small and midsize businesses.',
    shortDescription: 'Paylocity is a HRIS system',
    category: 'HRIS & Ben Admin',
    isActive: false,
  },
  {
    name: 'Sapling',
    icon: icons.saplingIcon,
    url: 'https://www.saplinghr.com/',
    description: 'Sapling is a cloud-based human resource (HR) software solution designed to assist in automating HR processes, managing employee information, and driving employee engagement.',
    shortDescription: 'Sapling is a HRIS system',
    category: 'HRIS',
    isActive: false,
  },
  {
    name: 'Wave',
    icon: icons.waveIcon,
    url: 'https://www.waveapps.com/',
    description: 'Wave is a cloud-based accounting and invoicing solution designed for small businesses. It offers billing and invoicing, payment tracking, payroll management, finance management, and receipts.',
    shortDescription: 'Wave is a accounting system',
    category: 'Ben Admin',
    isActive: false,
  },
  {
    name: 'AccuPay',
    icon: icons.accuPayIcon,
    url: 'https://www.accupay.com/',
    description: 'AccuPay is a cloud-based payroll solution designed for small and midsize businesses. It offers tax management, payroll management, time and attendance tracking, and HR management functionalities within a suite.',
    shortDescription: 'AccuPay is a payroll system',
    category: 'Payroll',
    isActive: false,
  },
  {
    name: 'AHOLA',
    icon: icons.aholaIcon,
    url: 'https://www.ahola.com/',
    description: 'AHOLA is a cloud-based payroll and human resource (HR) management solution designed for small and midsize businesses. It offers tax filing and payroll processing functionalities within a suite.',
    shortDescription: 'AHOLA is a payroll system',
    category: 'Payroll',
    isActive: false,
  },
  {
    name: 'BambooHR',
    icon: icons.bamboohrIcon,
    url: 'https://www.bamboohr.com/',
    description: 'BambooHR is a cloud-based human resources (HR) software service for small and midsize businesses. BambooHR offers small and growing companies a human resource information system (HRIS) that includes an applicant tracking system (ATS) and HRIS tools to manage all aspects of the employee lifecycle.',
    shortDescription: 'BambooHR is a HRIS system',
    category: 'HRIS & Ben Admin',
    isActive: false,
  },
  {
    name: 'Gusto',
    icon: icons.gustoIcon,
    url: 'https://gusto.com/',
    description: 'Gusto is a cloud-based payroll, benefits, and human resource management solution for businesses of any size. It offers tools to manage employee onboarding, offboarding, time tracking, payroll, and more.',
    shortDescription: 'Gusto is a payroll system',
    category: 'Payroll',
  },
  {
    name: 'Justworks',
    icon: icons.justworksIcon,
    url: 'https://justworks.com/',
    description: 'Justworks is a cloud-based human resources solution that helps small businesses to manage payroll, benefits and compliance functions. It allows users to manage employee benefits plans, such as health insurance, workers\' compensation, and 401(k) retirement plans.',
    shortDescription: 'Justworks is a HRIS system',
    category: 'HRIS & Ben Admin',
  },
  {
    name: 'Namely',
    icon: icons.namelyIcon,
    url: 'https://www.namely.com/',
    description: 'Namely is a cloud-based solution for companies seeking a single comprehensive system to manage their human capital. Namely helps midsize companies manage compliance and streamline everything payroll, benefits and talent management.',
    shortDescription: 'Namely is a HRIS system',
    category: 'HRIS',
  },
  {
    name: 'Humaans',
    icon: icons.humaansIcon,
    url: 'https://www.humaans.io/',
    description: 'Humaans is a cloud-based human resource management solution that helps businesses of all sizes manage and streamline processes related to employee onboarding, offboarding, compensation, and more.',
    shortDescription: 'Humaans is a HRIS system',
    category: 'HRIS',
  }
]