import { createAction } from "@reduxjs/toolkit"
export const setStep = createAction<any>('company/setStep')
export const setCompanyDetails = createAction<any>('company/setCompanyDetails')
export const setBenefits = createAction<any>('company/setBenefits')
export const setIntegration = createAction<any>('company/setIntegrations')
export const setEmployees = createAction<any>('company/setEmployees')
export const toggleBenefitActivation = createAction<any>('company/toggleBenefitActivation')
export const removeIntegration = createAction<any>('company/removeIntegration')
export const updateBenefit = createAction<any>('company/updateBenefit')
export const addIntegrations = createAction<any>('company/addIntegrations')
export const setUserProfile = createAction<any>('company/setUserProfile')
export const setCompanyPlan = createAction<any>('company/setCompanyPlan')
export const setCompanyPaymentMethod = createAction<any>('company/setCompanyPaymentMethod')
export const setCurrentEmployee = createAction<any>('company/setCurrentEmployee')