import { createAction } from "@reduxjs/toolkit"
export const setStep = createAction<any>('onboarding/setStep')
export const setCompanyDetails = createAction<any>('onboarding/setCompanyDetails')
export const setBenefits = createAction<any>('onboarding/setBenefits')
export const setIntegration = createAction<any>('onboarding/setIntegrations')
export const setEmployees = createAction<any>('onboarding/setEmployees')
export const toggleBenefitActivation = createAction<any>('onboarding/toggleBenefitActivation')
export const removeIntegration = createAction<any>('onboarding/removeIntegration')
export const updateBenefit = createAction<any>('onboarding/updateBenefit')
export const addIntegrations = createAction<any>('onboarding/addIntegrations')
export const setUserProfile = createAction<any>('onboarding/setUserProfile')
export const setCompanyPlan = createAction<any>('onboarding/setCompanyPlan')
export const setCompanyPaymentMethod = createAction<any>('onboarding/setCompanyPaymentMethod')